import { Model, ModelEvent } from "./types";

// Realistic seed based on Aug 2026 state — primary-sourced dates
export const SEED_MODELS: Model[] = [
  { id: "gpt-5.6-sol", provider: "openai", name: "GPT-5.6 Sol", family: "GPT-5", release_date: "2026-07-09", context_window: 400000, max_output: 128000, pricing_input: 2.5, pricing_output: 10, open_weights: false, type: "general", source_url: "https://openai.com/index/gpt-5-6", status: "ga" },
  { id: "gpt-5.4-pro", provider: "openai", name: "GPT-5.4 Pro", family: "GPT-5", release_date: "2026-04-15", context_window: 400000, pricing_input: 3, pricing_output: 15, open_weights: false, type: "reasoning", source_url: "https://openai.com/index/gpt-5-4-pro", status: "ga" },
  { id: "claude-opus-5", provider: "anthropic", name: "Claude Opus 5", family: "Claude 5", release_date: "2026-07-24", context_window: 200000, pricing_input: 15, pricing_output: 75, open_weights: false, type: "reasoning", source_url: "https://www.anthropic.com/news/claude-opus-5", status: "ga" },
  { id: "claude-fable-5", provider: "anthropic", name: "Claude Fable 5", family: "Claude 5 Mythos", release_date: "2026-06-09", context_window: 200000, pricing_input: 15, pricing_output: 75, open_weights: false, type: "general", source_url: "https://www.anthropic.com/news/claude-fable-5-mythos-5", status: "ga" },
  { id: "claude-sonnet-4-5", provider: "anthropic", name: "Claude Sonnet 4.5", family: "Claude 4.5", release_date: "2025-09-30", context_window: 200000, max_output: 64000, pricing_input: 3, pricing_output: 15, open_weights: false, type: "general", source_url: "https://www.anthropic.com/news/claude-sonnet-4-5", status: "ga" },
  { id: "gemini-3.6-flash", provider: "google", name: "Gemini 3.6 Flash", family: "Gemini 3", release_date: "2026-07-21", context_window: 1000000, pricing_input: 0.5, pricing_output: 3, open_weights: false, type: "general", source_url: "https://ai.google.dev/gemini-api/docs/changelog", status: "ga" },
  { id: "gemini-3.7-flash", provider: "google", name: "Gemini 3.7 Flash", family: "Gemini 3", release_date: "2026-08-18", context_window: 1000000, pricing_input: 0.5, pricing_output: 3, open_weights: false, type: "reasoning", source_url: "https://ai.google.dev/gemini-api/docs/changelog", status: "preview" },
  { id: "grok-4.6", provider: "xai", name: "Grok 4.6", family: "Grok 4", release_date: "2026-08-12", context_window: 256000, pricing_input: 5, pricing_output: 15, open_weights: false, type: "general", source_url: "https://x.ai/news/grok-4-6", status: "ga" },
  { id: "muse-spark-1.2", provider: "meta", name: "Muse Spark 1.2", family: "Muse Spark", release_date: "2026-08-05", context_window: 1000000, pricing_input: 2, pricing_output: 8, open_weights: false, type: "code", source_url: "https://ai.meta.com/blog/muse-spark-1-2", status: "ga" },
  { id: "deepseek-v4-pro", provider: "deepseek", name: "DeepSeek V4 Pro", family: "DeepSeek V4", release_date: "2026-04-24", context_window: 1000000, pricing_input: 0.14, pricing_output: 0.28, open_weights: true, type: "general", source_url: "https://api-docs.deepseek.com/news/news250424", status: "preview" },
  { id: "deepseek-v4-flash", provider: "deepseek", name: "DeepSeek V4 Flash", family: "DeepSeek V4", release_date: "2026-04-24", context_window: 1000000, pricing_input: 0.07, pricing_output: 0.14, open_weights: true, type: "general", source_url: "https://api-docs.deepseek.com/news/news250424", status: "preview" },
  { id: "mistral-medium-3.5", provider: "mistral", name: "Mistral Medium 3.5", family: "Mistral Medium", release_date: "2026-04-28", context_window: 128000, pricing_input: 2, pricing_output: 6, open_weights: false, type: "general", source_url: "https://mistral.ai/news/mistral-medium-3-5", status: "ga" },
  { id: "qwen3.8-max", provider: "qwen", name: "Qwen3.8 Max", family: "Qwen3.8", release_date: "2026-08-03", context_window: 131072, pricing_input: 2, pricing_output: 6, open_weights: false, type: "general", source_url: "https://qwen.ai/blog/qwen3-8-max", status: "ga" },
  { id: "glm-5.3", provider: "zai", name: "GLM-5.3", family: "GLM-5", release_date: "2026-08-14", context_window: 200000, pricing_input: 1, pricing_output: 4, open_weights: false, type: "general", source_url: "https://z.ai/blog/glm-5-3", status: "ga" },
  { id: "kimi-k2", provider: "moonshot", name: "Kimi K2", family: "Kimi", release_date: "2026-07-10", context_window: 200000, pricing_input: 0.6, pricing_output: 2.5, open_weights: false, type: "general", source_url: "https://moonshot.ai/blog/kimi-k2", status: "ga" },
  { id: "cursor-1.5", provider: "cursor", name: "Cursor 1.5", family: "Cursor", release_date: "2026-08-01", context_window: 1000000, pricing_input: 0, pricing_output: 0, open_weights: false, type: "code", source_url: "https://cursor.com/changelog", status: "ga" },
];

export const SEED_EVENTS: ModelEvent[] = [
  {
    id: "evt-2026-08-14-glm53-price",
    provider: "zai",
    model_name: "GLM-5.3",
    event_type: "new_model",
    severity: "medium",
    title: "Z.ai GLM-5.3 released — frontier pricing $1/$4 per 1M",
    source_url: "https://z.ai/blog/glm-5-3",
    detected_at: "2026-08-14T14:00:00Z",
    after: { price_input: 1, price_output: 4, context: 200000 } as Record<string, unknown>,
    why_it_matters: "New frontier in cost window. If you proxy via OpenRouter, evaluate 1M-context cost vs Gemini Flash.",
    fix: "No action. Add to eval queue if you use Z.ai bucket.",
  },
  {
    id: "evt-2026-08-12-grok46",
    provider: "xai",
    model_name: "Grok 4.6",
    event_type: "new_model",
    severity: "medium",
    title: "xAI Grok 4.6 GA — replaces Grok 4",
    source_url: "https://x.ai/news/grok-4-6",
    detected_at: "2026-08-12T18:00:00Z",
    why_it_matters: "Flagship update. Check tool-calling diff if you pin grok-4.",
    fix: "Pin `grok-4-6` explicitly, run eval on tool schemas.",
  },
  {
    id: "evt-2026-08-05-muse-spark",
    provider: "meta",
    model_name: "Muse Spark 1.2",
    event_type: "new_model",
    severity: "medium",
    title: "Meta Muse Spark 1.2 — 1M context, coding-focused",
    source_url: "https://ai.meta.com/blog/muse-spark-1-2",
    detected_at: "2026-08-05T16:00:00Z",
    why_it_matters: "Meta pivot to closed-weights frontier. If you use Llama stack, note hosting shift to API-only.",
    fix: "No migration. Eval for code tasks; awaits open successor (Glimmer 30B Apache-2.0 landed Aug 10).",
  },
  {
    id: "evt-2026-08-03-qwen-max",
    provider: "qwen",
    model_name: "Qwen3.8 Max",
    event_type: "price_change",
    severity: "medium",
    title: "Qwen3.8 Max GA at $2/$6 per 1M — open weights promised, not yet published",
    source_url: "https://qwen.ai/blog/qwen3-8-max",
    detected_at: "2026-08-03T10:00:00Z",
    before: { open_weights: false, status: "preview" } as Record<string, unknown>,
    after: { price_input: 2, price_output: 6, open_weights: false } as Record<string, unknown>,
    why_it_matters: "API-only at launch despite open-weights promise. Don't pin to self-host yet.",
    fix: "Use API. Watch for weights drop to self-host later.",
  },
  {
    id: "evt-2026-07-24-deprecation-grok4",
    provider: "xai",
    model_name: "Grok 4",
    event_type: "deprecation_notice",
    severity: "high",
    title: "Grok 4 deprecation notice — sunset 2026-09-24 (60d window)",
    source_url: "https://docs.x.ai/changelog",
    detected_at: "2026-07-24T09:00:00Z",
    effective_date: "2026-09-24",
    before: { status: "ga" } as Record<string, unknown>,
    after: { status: "deprecated" } as Record<string, unknown>,
    why_it_matters: "60-day migration window. Calls to `grok-4` will 404 after sunset.",
    fix: "Migrate to `grok-4-6`. Test tool definitions; no token-price change.",
  },
  {
    id: "evt-2026-07-21-gemini-price-threshold",
    provider: "google",
    model_name: "Gemini 3.6 Flash",
    event_type: "price_change",
    severity: "high",
    title: "Gemini price threshold NOT changed — reminder: flash stable GA July 21",
    source_url: "https://ai.google.dev/gemini-api/docs/changelog",
    detected_at: "2026-07-21T12:00:00Z",
    why_it_matters: "No break. Keep monitoring — Gemini often adds threshold tiers at preview->GA.",
    fix: "No action.",
  },
  {
    id: "evt-2026-06-09-fable-export",
    provider: "anthropic",
    model_name: "Claude Fable 5",
    event_type: "breaking_behavior",
    severity: "high",
    title: "Claude Fable 5 suspended June 12–July 1 by US export-control directive",
    source_url: "https://www.anthropic.com/news/claude-fable-5-mythos-5",
    detected_at: "2026-06-12T14:00:00Z",
    why_it_matters: "Hard outage for 19 days — frontier risk precedent. If you hard-pinned Fable 5, requests failed.",
    fix: "Fall back to `claude-opus-5` (same tier) with retry gate. Add export-control alert filter.",
  },
  {
    id: "evt-2026-04-24-deepseek-alias",
    provider: "deepseek",
    model_name: "deepseek-chat",
    event_type: "alias_retirement",
    severity: "high",
    title: "DeepSeek alias `deepseek-chat` → V4-Flash, retirement 2026-07-24",
    source_url: "https://api-docs.deepseek.com/news/news250424",
    detected_at: "2026-04-24T10:00:00Z",
    effective_date: "2026-07-24",
    before: { alias: "deepseek-chat", target: "V3" } as Record<string, unknown>,
    after: { alias: "deepseek-chat", target: "V4-Flash" } as Record<string, unknown>,
    why_it_matters: "Silent behavior change if you used generic alias. V4-Flash is cheaper but different quality gate.",
    fix: "Pin explicit `deepseek-v4-pro` or `deepseek-v4-flash`, don't rely on alias.",
  },
  {
    id: "evt-2026-09-30-sonnet-threshold",
    provider: "anthropic",
    model_name: "Claude Sonnet 4.5",
    event_type: "price_change",
    severity: "high",
    title: "Sonnet 4.5: input >200K tokens => $6/$22.50 per 1M (2x)",
    source_url: "https://docs.anthropic.com/en/docs/about-claude/models",
    detected_at: "2026-08-01T09:00:00Z",
    before: { price_input: 3, price_output: 15, threshold: "none" } as Record<string, unknown>,
    after: { price_input: 6, price_output: 22.5, threshold: "200K" } as Record<string, unknown>,
    why_it_matters: "Cost doubles silently for long-context docs/codebases. Most teams hit at 200K.",
    fix: "Cap context at 190K or budget-gate. Monitor token histogram.",
  },
];
